In [ ]:
pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
dados_catalogo = {
'ID_Titulo': [101, 102, 103, 104, 105, 106, 101, 107, 108],
'Titulo': ['Stranger Things', 'O Poderoso Chefão', 'Interestelar', 'Breaking Bad', 'Duna', 'Succession', 'Stranger Things', 'Toy Story', 'Vingadores: Ultimato'],
'Tipo': ['Série', 'Filme', 'Filme', 'Série', 'Filme', 'Série', 'Série', 'Filme', 'Filme'],
'Ano': [2016, 1972, np.nan, 2008, 2021, 2018, 2016, 1995, 2019],
'Genero': ['Ficção Científica', np.nan, 'Ficção Científica', 'Drama', 'Ficção Científica', 'Drama', 'Ficção Científica', 'Animação', 'Ação'],
'Plataforma': ['Netflix', 'Prime Video', 'Prime Video', 'Netflix', 'HBO Max', 'HBO Max', 'Netflix', 'Disney+', 'Disney+']
}
df_catalogo = pd.DataFrame(dados_catalogo)

display(df_catalogo)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix
1,102,O Poderoso Chefão,Filme,1972.0,NaN,Prime Video
2,103,Interestelar,Filme,NaN,Ficção Científica,Prime Video
3,104,Breaking Bad,Série,2008.0,Drama,Netflix
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max
5,106,Succession,Série,2018.0,Drama,HBO Max
6,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix
7,107,Toy Story,Filme,1995.0,Animação,Disney+
8,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+

In [4]:
dados_metricas = {
'ID_Titulo': [101, 102, 103, 104, 105, 106, 107, 109], # O ID 109 é de um filme que não está no catálogo
'Nota_IMDb': [8.7, 9.2, 8.6, 9.5, 8.0, 8.8, 8.3, 9.0],
'Votos_Milhares': [1200, 1900, 1500, 1800, 700, 450, 600, 950],
'Orcamento_Milhoes': [12.0, 6.0, 165.0, 3.0, 165.0, 9.0, 30.0, 180.0]
}
df_metricas = pd.DataFrame(dados_metricas)
print("Tabelas carregadas com sucesso! Pronto para iniciar a análise.")

display(df_metricas)

Tabelas carregadas com sucesso! Pronto para iniciar a análise.

   ID_Titulo  Nota_IMDb  Votos_Milhares  Orcamento_Milhoes
0        101        8.7            1200               12.0
1        102        9.2            1900                6.0
2        103        8.6            1500              165.0
3        104        9.5            1800                3.0
4        105        8.0             700              165.0
5        106        8.8             450                9.0
6        107        8.3             600               30.0
7        109        9.0             950              180.0

In [5]:
#FASE 01
#1
print(df_catalogo.duplicated().sum()) 
df_catalogo = df_catalogo.drop_duplicates()
display(df_catalogo)

1

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix
1,102,O Poderoso Chefão,Filme,1972.0,NaN,Prime Video
2,103,Interestelar,Filme,NaN,Ficção Científica,Prime Video
3,104,Breaking Bad,Série,2008.0,Drama,Netflix
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max
5,106,Succession,Série,2018.0,Drama,HBO Max
7,107,Toy Story,Filme,1995.0,Animação,Disney+
8,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+

In [6]:
#2 
df_catalogo['Genero'] = df_catalogo['Genero'].fillna('Clássico')
display(df_catalogo)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video
2,103,Interestelar,Filme,NaN,Ficção Científica,Prime Video
3,104,Breaking Bad,Série,2008.0,Drama,Netflix
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max
5,106,Succession,Série,2018.0,Drama,HBO Max
7,107,Toy Story,Filme,1995.0,Animação,Disney+
8,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+

In [7]:
#3
df_catalogo['Ano'] = df_catalogo['Ano'].fillna(2014)
display(df_catalogo)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video
3,104,Breaking Bad,Série,2008.0,Drama,Netflix
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max
5,106,Succession,Série,2018.0,Drama,HBO Max
7,107,Toy Story,Filme,1995.0,Animação,Disney+
8,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+

In [8]:
#4
print(df_catalogo.isnull().sum())

ID_Titulo     0
Titulo        0
Tipo          0
Ano           0
Genero        0
Plataforma    0
dtype: int64

In [13]:
#FASE 02
#1
print(df_catalogo.loc[:2,['Titulo', 'Plataforma']])
print()
print()
print(df_catalogo.iloc[4, 1])

              Titulo   Plataforma
0    Stranger Things      Netflix
1  O Poderoso Chefão  Prime Video
2       Interestelar  Prime Video


Duna

In [23]:
#2
print(df_catalogo[(df_catalogo['Genero'] == 'Ficção Científica') & (df_catalogo['Ano'] >= 2015)])

   ID_Titulo           Titulo   Tipo     Ano             Genero Plataforma
0        101  Stranger Things  Série  2016.0  Ficção Científica    Netflix
4        105             Duna  Filme  2021.0  Ficção Científica    HBO Max

In [21]:
#3
def categoria_orcamento(n):
    if n < 10:
        return 'Baixo Custo'
    
    elif n >= 10 and n < 100:
        return 'Médio Custo'
    
    elif n >= 100:
        return 'Blockbuster'

In [16]:
#FASE 04
#1
df_consolidado = pd.merge(df_catalogo, df_metricas, on='ID_Titulo', how='left')
display(df_consolidado)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma,Nota_IMDb,Votos_Milhares,Orcamento_Milhoes
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix,8.7,1200.0,12.0
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video,9.2,1900.0,6.0
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video,8.6,1500.0,165.0
3,104,Breaking Bad,Série,2008.0,Drama,Netflix,9.5,1800.0,3.0
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max,8.0,700.0,165.0
5,106,Succession,Série,2018.0,Drama,HBO Max,8.8,450.0,9.0
6,107,Toy Story,Filme,1995.0,Animação,Disney+,8.3,600.0,30.0
7,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+,NaN,NaN,NaN

In [17]:
#2
df_consolidado['Nota_IMDb'] = df_consolidado['Nota_IMDb'].fillna(df_consolidado['Nota_IMDb'].mean())
df_consolidado['Votos_Milhares'] = df_consolidado['Votos_Milhares'].fillna(df_consolidado['Votos_Milhares'].mean())
df_consolidado['Orcamento_Milhoes'] = df_consolidado['Orcamento_Milhoes'].fillna(0.0)
display(df_consolidado)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma,Nota_IMDb,Votos_Milhares,Orcamento_Milhoes
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix,8.700000,1200.000000,12.0
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video,9.200000,1900.000000,6.0
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video,8.600000,1500.000000,165.0
3,104,Breaking Bad,Série,2008.0,Drama,Netflix,9.500000,1800.000000,3.0
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max,8.000000,700.000000,165.0
5,106,Succession,Série,2018.0,Drama,HBO Max,8.800000,450.000000,9.0
6,107,Toy Story,Filme,1995.0,Animação,Disney+,8.300000,600.000000,30.0
7,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+,8.728571,1164.285714,0.0

In [18]:
#3
print(df_consolidado.groupby('Genero').count())

                   ID_Titulo  Titulo  Tipo  Ano  Plataforma  Nota_IMDb  \
Genero
Animação                   1       1     1    1           1          1
Ação                       1       1     1    1           1          1
Clássico                   1       1     1    1           1          1
Drama                      2       2     2    2           2          2
Ficção Científica          3       3     3    3           3          3

                   Votos_Milhares  Orcamento_Milhoes
Genero
Animação                        1                  1
Ação                            1                  1
Clássico                        1                  1
Drama                           2                  2
Ficção Científica               3                  3

In [19]:
#4
soma_total_orcamento = df_consolidado.groupby('Genero')['Orcamento_Milhoes'].sum()
print('Soma total dos orçamentos: ')
print()
print(soma_total_orcamento)
print()
media_notas_genero = df_consolidado.groupby('Genero')['Nota_IMDb'].mean()
print('Média das notas: ')
print()
print(media_notas_genero)
print()
print("Gênero com maior orçamento:", soma_total_orcamento.idxmax())
print("Gênero com melhor nota média:", media_notas_genero.idxmax())

Soma total dos orçamentos:

Genero
Animação              30.0
Ação                   0.0
Clássico               6.0
Drama                 12.0
Ficção Científica    342.0
Name: Orcamento_Milhoes, dtype: float64

Média das notas:

Genero
Animação             8.300000
Ação                 8.728571
Clássico             9.200000
Drama                9.150000
Ficção Científica    8.433333
Name: Nota_IMDb, dtype: float64

Gênero com maior orçamento: Ficção Científica
Gênero com melhor nota média: Clássico

In [22]:
#5
df_consolidado['Perfil_Financeiro'] = df_consolidado['Orcamento_Milhoes'].apply(categoria_orcamento)
display(df_consolidado)

,ID_Titulo,Titulo,Tipo,Ano,Genero,Plataforma,Nota_IMDb,Votos_Milhares,Orcamento_Milhoes,Perfil_Financeiro
0,101,Stranger Things,Série,2016.0,Ficção Científica,Netflix,8.700000,1200.000000,12.0,Médio Custo
1,102,O Poderoso Chefão,Filme,1972.0,Clássico,Prime Video,9.200000,1900.000000,6.0,Baixo Custo
2,103,Interestelar,Filme,2014.0,Ficção Científica,Prime Video,8.600000,1500.000000,165.0,Blockbuster
3,104,Breaking Bad,Série,2008.0,Drama,Netflix,9.500000,1800.000000,3.0,Baixo Custo
4,105,Duna,Filme,2021.0,Ficção Científica,HBO Max,8.000000,700.000000,165.0,Blockbuster
5,106,Succession,Série,2018.0,Drama,HBO Max,8.800000,450.000000,9.0,Baixo Custo
6,107,Toy Story,Filme,1995.0,Animação,Disney+,8.300000,600.000000,30.0,Médio Custo
7,108,Vingadores: Ultimato,Filme,2019.0,Ação,Disney+,8.728571,1164.285714,0.0,Baixo Custo